//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Async_Controller_Prj.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer2
    {
        public int customerId { get; set; }
        public string customerName { get; set; }
        public Nullable<byte> customerAge { get; set; }
        public string cAddress { get; set; }
        public Nullable<long> cPhoneNumber { get; set; }
    }
}
