// <auto-generated />
namespace MVC_CodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Columnadded_Product : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Columnadded_Product));
        
        string IMigrationMetadata.Id
        {
            get { return "202601060531445_Columnadded_Product"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
