//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServices_Client.Web_Infinite {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Web_Infinite.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        WebServices_Client.Web_Infinite.HelloWorldResponse HelloWorld(WebServices_Client.Web_Infinite.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServices_Client.Web_Infinite.HelloWorldResponse> HelloWorldAsync(WebServices_Client.Web_Infinite.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name SayHelloResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SayHello", ReplyAction="*")]
        WebServices_Client.Web_Infinite.SayHelloResponse SayHello(WebServices_Client.Web_Infinite.SayHelloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SayHello", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServices_Client.Web_Infinite.SayHelloResponse> SayHelloAsync(WebServices_Client.Web_Infinite.SayHelloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Squareroot", ReplyAction="*")]
        float Squareroot(float f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Squareroot", ReplyAction="*")]
        System.Threading.Tasks.Task<float> SquarerootAsync(float f);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public WebServices_Client.Web_Infinite.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(WebServices_Client.Web_Infinite.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebServices_Client.Web_Infinite.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(WebServices_Client.Web_Infinite.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SayHelloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SayHello", Namespace="http://tempuri.org/", Order=0)]
        public WebServices_Client.Web_Infinite.SayHelloRequestBody Body;
        
        public SayHelloRequest() {
        }
        
        public SayHelloRequest(WebServices_Client.Web_Infinite.SayHelloRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SayHelloRequestBody {
        
        public SayHelloRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SayHelloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SayHelloResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebServices_Client.Web_Infinite.SayHelloResponseBody Body;
        
        public SayHelloResponse() {
        }
        
        public SayHelloResponse(WebServices_Client.Web_Infinite.SayHelloResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SayHelloResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SayHelloResult;
        
        public SayHelloResponseBody() {
        }
        
        public SayHelloResponseBody(string SayHelloResult) {
            this.SayHelloResult = SayHelloResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : WebServices_Client.Web_Infinite.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<WebServices_Client.Web_Infinite.WebServiceSoap>, WebServices_Client.Web_Infinite.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServices_Client.Web_Infinite.HelloWorldResponse WebServices_Client.Web_Infinite.WebServiceSoap.HelloWorld(WebServices_Client.Web_Infinite.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            WebServices_Client.Web_Infinite.HelloWorldRequest inValue = new WebServices_Client.Web_Infinite.HelloWorldRequest();
            inValue.Body = new WebServices_Client.Web_Infinite.HelloWorldRequestBody();
            WebServices_Client.Web_Infinite.HelloWorldResponse retVal = ((WebServices_Client.Web_Infinite.WebServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServices_Client.Web_Infinite.HelloWorldResponse> WebServices_Client.Web_Infinite.WebServiceSoap.HelloWorldAsync(WebServices_Client.Web_Infinite.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServices_Client.Web_Infinite.HelloWorldResponse> HelloWorldAsync() {
            WebServices_Client.Web_Infinite.HelloWorldRequest inValue = new WebServices_Client.Web_Infinite.HelloWorldRequest();
            inValue.Body = new WebServices_Client.Web_Infinite.HelloWorldRequestBody();
            return ((WebServices_Client.Web_Infinite.WebServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServices_Client.Web_Infinite.SayHelloResponse WebServices_Client.Web_Infinite.WebServiceSoap.SayHello(WebServices_Client.Web_Infinite.SayHelloRequest request) {
            return base.Channel.SayHello(request);
        }
        
        public string SayHello() {
            WebServices_Client.Web_Infinite.SayHelloRequest inValue = new WebServices_Client.Web_Infinite.SayHelloRequest();
            inValue.Body = new WebServices_Client.Web_Infinite.SayHelloRequestBody();
            WebServices_Client.Web_Infinite.SayHelloResponse retVal = ((WebServices_Client.Web_Infinite.WebServiceSoap)(this)).SayHello(inValue);
            return retVal.Body.SayHelloResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServices_Client.Web_Infinite.SayHelloResponse> WebServices_Client.Web_Infinite.WebServiceSoap.SayHelloAsync(WebServices_Client.Web_Infinite.SayHelloRequest request) {
            return base.Channel.SayHelloAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServices_Client.Web_Infinite.SayHelloResponse> SayHelloAsync() {
            WebServices_Client.Web_Infinite.SayHelloRequest inValue = new WebServices_Client.Web_Infinite.SayHelloRequest();
            inValue.Body = new WebServices_Client.Web_Infinite.SayHelloRequestBody();
            return ((WebServices_Client.Web_Infinite.WebServiceSoap)(this)).SayHelloAsync(inValue);
        }
        
        public float Squareroot(float f) {
            return base.Channel.Squareroot(f);
        }
        
        public System.Threading.Tasks.Task<float> SquarerootAsync(float f) {
            return base.Channel.SquarerootAsync(f);
        }
    }
}
