//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_DatabaseFirst.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Infinite2025Entities1 : DbContext
    {
        public Infinite2025Entities1()
            : base("name=Infinite2025Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BankAccount> BankAccounts { get; set; }
        public virtual DbSet<Customer2> Customer2 { get; set; }
        public virtual DbSet<Customers1> Customers1 { get; set; }
        public virtual DbSet<Customersx> Customersxes { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Employees2> Employees2 { get; set; }
        public virtual DbSet<errorlog> errorlogs { get; set; }
        public virtual DbSet<NewProduct> NewProducts { get; set; }
        public virtual DbSet<Orders1> Orders1 { get; set; }
        public virtual DbSet<Orders2> Orders2 { get; set; }
        public virtual DbSet<Orders3> Orders3 { get; set; }
        public virtual DbSet<Orders4> Orders4 { get; set; }
        public virtual DbSet<Products2> Products2 { get; set; }
        public virtual DbSet<Sale> Sales { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<tblProduct> tblProducts { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Purchase> Purchases { get; set; }
        public virtual DbSet<storelog> storelogs { get; set; }
        public virtual DbSet<tblExceptionLog> tblExceptionLogs { get; set; }
        public virtual DbSet<testing> testings { get; set; }
    
        [DbFunction("Infinite2025Entities1", "fn_getStudents")]
        public virtual IQueryable<fn_getStudents_Result> fn_getStudents(string a)
        {
            var aParameter = a != null ?
                new ObjectParameter("a", a) :
                new ObjectParameter("a", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_getStudents_Result>("[Infinite2025Entities1].[fn_getStudents](@a)", aParameter);
        }
    
        [DbFunction("Infinite2025Entities1", "GetLastNYearsOrders")]
        public virtual IQueryable<GetLastNYearsOrders_Result> GetLastNYearsOrders(Nullable<int> n)
        {
            var nParameter = n.HasValue ?
                new ObjectParameter("n", n) :
                new ObjectParameter("n", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetLastNYearsOrders_Result>("[Infinite2025Entities1].[GetLastNYearsOrders](@n)", nParameter);
        }
    
        [DbFunction("Infinite2025Entities1", "test")]
        public virtual IQueryable<test_Result> test()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<test_Result>("[Infinite2025Entities1].[test]()");
        }
    
        public virtual int AddProduct(Nullable<int> a, Nullable<int> b)
        {
            var aParameter = a.HasValue ?
                new ObjectParameter("a", a) :
                new ObjectParameter("a", typeof(int));
    
            var bParameter = b.HasValue ?
                new ObjectParameter("b", b) :
                new ObjectParameter("b", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddProduct", aParameter, bParameter);
        }
    
        public virtual int Addproduct2(Nullable<int> a, Nullable<int> b)
        {
            var aParameter = a.HasValue ?
                new ObjectParameter("a", a) :
                new ObjectParameter("a", typeof(int));
    
            var bParameter = b.HasValue ?
                new ObjectParameter("b", b) :
                new ObjectParameter("b", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Addproduct2", aParameter, bParameter);
        }
    
        public virtual int Addproduct3(Nullable<int> a, Nullable<int> b, ObjectParameter c, ObjectParameter d)
        {
            var aParameter = a.HasValue ?
                new ObjectParameter("a", a) :
                new ObjectParameter("a", typeof(int));
    
            var bParameter = b.HasValue ?
                new ObjectParameter("b", b) :
                new ObjectParameter("b", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Addproduct3", aParameter, bParameter, c, d);
        }
    
        public virtual int displaydata(string tbl)
        {
            var tblParameter = tbl != null ?
                new ObjectParameter("tbl", tbl) :
                new ObjectParameter("tbl", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("displaydata", tblParameter);
        }
    
        public virtual int divide(Nullable<int> a, Nullable<int> b)
        {
            var aParameter = a.HasValue ?
                new ObjectParameter("a", a) :
                new ObjectParameter("a", typeof(int));
    
            var bParameter = b.HasValue ?
                new ObjectParameter("b", b) :
                new ObjectParameter("b", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("divide", aParameter, bParameter);
        }
    
        public virtual int ExceptionLoggingTodatabase(string excmsg, string exctype, string excsrc, string excurl)
        {
            var excmsgParameter = excmsg != null ?
                new ObjectParameter("excmsg", excmsg) :
                new ObjectParameter("excmsg", typeof(string));
    
            var exctypeParameter = exctype != null ?
                new ObjectParameter("exctype", exctype) :
                new ObjectParameter("exctype", typeof(string));
    
            var excsrcParameter = excsrc != null ?
                new ObjectParameter("excsrc", excsrc) :
                new ObjectParameter("excsrc", typeof(string));
    
            var excurlParameter = excurl != null ?
                new ObjectParameter("excurl", excurl) :
                new ObjectParameter("excurl", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ExceptionLoggingTodatabase", excmsgParameter, exctypeParameter, excsrcParameter, excurlParameter);
        }
    
        public virtual ObjectResult<getbyaddress_Result> getbyaddress(string a)
        {
            var aParameter = a != null ?
                new ObjectParameter("a", a) :
                new ObjectParameter("a", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getbyaddress_Result>("getbyaddress", aParameter);
        }
    
        public virtual ObjectResult<GetCustomerByRow_Result> GetCustomerByRow(Nullable<int> startRow, Nullable<int> endRow)
        {
            var startRowParameter = startRow.HasValue ?
                new ObjectParameter("startRow", startRow) :
                new ObjectParameter("startRow", typeof(int));
    
            var endRowParameter = endRow.HasValue ?
                new ObjectParameter("EndRow", endRow) :
                new ObjectParameter("EndRow", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCustomerByRow_Result>("GetCustomerByRow", startRowParameter, endRowParameter);
        }
    
        public virtual ObjectResult<getcustomers_Result> getcustomers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getcustomers_Result>("getcustomers");
        }
    
        public virtual ObjectResult<GetOrders_Result> GetOrders(Nullable<int> customer_id, ObjectParameter order_id, ObjectParameter quantity)
        {
            var customer_idParameter = customer_id.HasValue ?
                new ObjectParameter("customer_id", customer_id) :
                new ObjectParameter("customer_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetOrders_Result>("GetOrders", customer_idParameter, order_id, quantity);
        }
    
        public virtual ObjectResult<GetOrdersByDateRange_Result> GetOrdersByDateRange(Nullable<System.DateTime> startdate, Nullable<System.DateTime> endDate)
        {
            var startdateParameter = startdate.HasValue ?
                new ObjectParameter("startdate", startdate) :
                new ObjectParameter("startdate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetOrdersByDateRange_Result>("GetOrdersByDateRange", startdateParameter, endDateParameter);
        }
    
        public virtual int InsertCustomer(Nullable<int> customerId, string customerName)
        {
            var customerIdParameter = customerId.HasValue ?
                new ObjectParameter("CustomerId", customerId) :
                new ObjectParameter("CustomerId", typeof(int));
    
            var customerNameParameter = customerName != null ?
                new ObjectParameter("CustomerName", customerName) :
                new ObjectParameter("CustomerName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertCustomer", customerIdParameter, customerNameParameter);
        }
    
        public virtual int myProc(string cname, Nullable<int> age)
        {
            var cnameParameter = cname != null ?
                new ObjectParameter("cname", cname) :
                new ObjectParameter("cname", typeof(string));
    
            var ageParameter = age.HasValue ?
                new ObjectParameter("age", age) :
                new ObjectParameter("age", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("myProc", cnameParameter, ageParameter);
        }
    
        public virtual int OrdersDetailsByCustId(Nullable<int> customerid, ObjectParameter quantity, ObjectParameter order_id)
        {
            var customeridParameter = customerid.HasValue ?
                new ObjectParameter("customerid", customerid) :
                new ObjectParameter("customerid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("OrdersDetailsByCustId", customeridParameter, quantity, order_id);
        }
    
        public virtual ObjectResult<pro3_Result> pro3(Nullable<int> customer_id)
        {
            var customer_idParameter = customer_id.HasValue ?
                new ObjectParameter("customer_id", customer_id) :
                new ObjectParameter("customer_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pro3_Result>("pro3", customer_idParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> pro4()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("pro4");
        }
    
        public virtual int sp_getdata()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_getdata");
        }
    
        public virtual int spAddEmployee(string name, string department, Nullable<decimal> salary, ObjectParameter newEmployeeID)
        {
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var departmentParameter = department != null ?
                new ObjectParameter("Department", department) :
                new ObjectParameter("Department", typeof(string));
    
            var salaryParameter = salary.HasValue ?
                new ObjectParameter("Salary", salary) :
                new ObjectParameter("Salary", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spAddEmployee", nameParameter, departmentParameter, salaryParameter, newEmployeeID);
        }
    
        public virtual ObjectResult<spGetProductByName_Result> spGetProductByName(string productname)
        {
            var productnameParameter = productname != null ?
                new ObjectParameter("Productname", productname) :
                new ObjectParameter("Productname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetProductByName_Result>("spGetProductByName", productnameParameter);
        }
    
        public virtual ObjectResult<spGetProducts_Result> spGetProducts()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetProducts_Result>("spGetProducts");
        }
    
        public virtual ObjectResult<spGetProductsByCategory_Result> spGetProductsByCategory(string product_name)
        {
            var product_nameParameter = product_name != null ?
                new ObjectParameter("product_name", product_name) :
                new ObjectParameter("product_name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetProductsByCategory_Result>("spGetProductsByCategory", product_nameParameter);
        }
    
        public virtual int spSafeOrderInsert(string product_name, Nullable<System.DateTime> order_date, Nullable<decimal> total_amount)
        {
            var product_nameParameter = product_name != null ?
                new ObjectParameter("product_name", product_name) :
                new ObjectParameter("product_name", typeof(string));
    
            var order_dateParameter = order_date.HasValue ?
                new ObjectParameter("order_date", order_date) :
                new ObjectParameter("order_date", typeof(System.DateTime));
    
            var total_amountParameter = total_amount.HasValue ?
                new ObjectParameter("total_amount", total_amount) :
                new ObjectParameter("total_amount", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spSafeOrderInsert", product_nameParameter, order_dateParameter, total_amountParameter);
        }
    
        public virtual int spUpdateSalary(Nullable<int> empId, Nullable<int> percentage)
        {
            var empIdParameter = empId.HasValue ?
                new ObjectParameter("EmpId", empId) :
                new ObjectParameter("EmpId", typeof(int));
    
            var percentageParameter = percentage.HasValue ?
                new ObjectParameter("percentage", percentage) :
                new ObjectParameter("percentage", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spUpdateSalary", empIdParameter, percentageParameter);
        }
    }
}
